### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by sometimes-i-send-pull-requests** [sbyt32/mtg_price_fetcher#14]
You already have testing on your plate. But for concreteness, here is an issue. I recommend using [pytest](https://pytest.org). In addition, I recommend adding [pytest-cov](https://pytest-cov.readthedocs.io/en/latest/index.html) to measure the test coverage of your code.

**Comment by sbyt32** [comment]
Added Testing w/ pytest + pytest-cov as of https://github.com/sbyt32/mtg_price_fetcher/commit/4fa790b693cd4c780c5003c4f3e88f01969cf3aa
